# Generated by Django 6.0.4 on 2026-04-21 22:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable label for the audit project.', max_length=255, verbose_name='project name')),
                ('description', models.TextField(blank=True, help_text='Optional notes or context about this project.', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(help_text='The user who created and owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The URL of the web-page home page that was analysed (FR-03).', max_length=2048, validators=[django.core.validators.URLValidator()], verbose_name='analysed URL')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the analysis was performed.', verbose_name='scanned at')),
                ('count_links', models.PositiveIntegerField(default=0, help_text='Number of internal navigation links extracted from the page (|L|).', verbose_name='link count (L)')),
                ('count_styles', models.PositiveIntegerField(default=0, help_text='Number of external CSS stylesheets found on the page (|S|).', verbose_name='style count (S)')),
                ('count_scripts', models.PositiveIntegerField(default=0, help_text='Number of client-side JS scripts referenced by the page (|Sc|).', verbose_name='script count (Sc)')),
                ('weight_links', models.DecimalField(decimal_places=4, default=Decimal('0.3333'), help_text='Relative importance of navigation links in the complexity formula. Must satisfy W_links + W_styles + W_scripts = 1.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='weight W_links')),
                ('weight_styles', models.DecimalField(decimal_places=4, default=Decimal('0.3333'), help_text='Relative importance of stylesheets in the complexity formula. Must satisfy W_links + W_styles + W_scripts = 1.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='weight W_styles')),
                ('weight_scripts', models.DecimalField(decimal_places=4, default=Decimal('0.3333'), help_text='Relative importance of scripts in the complexity formula. Must satisfy W_links + W_styles + W_scripts = 1.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('1.0'))], verbose_name='weight W_scripts')),
                ('complexity_index', models.DecimalField(blank=True, decimal_places=4, help_text='Architectural Complexity Index C = Σ W_i * N_i as defined in Section 1.3.4. Populated automatically by save_with_complexity().', max_digits=12, null=True, verbose_name='complexity index (C)')),
                ('raw_metadata', models.JSONField(blank=True, help_text='Serialised WP tuple {links: [...], styles: [...], scripts: [...]} for audit trail and future re-analysis.', null=True, verbose_name='raw metadata')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who triggered this analysis run (FR-01).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('project', models.ForeignKey(help_text='The audit project this scan belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'analysis report',
                'verbose_name_plural': 'analysis reports',
                'ordering': ['-scanned_at'],
                'indexes': [models.Index(fields=['project', '-scanned_at'], name='idx_report_project_time')],
            },
        ),
    ]
